// generated 2003/5/16 19:57:35 EDT by sean@blue.localhost.(none)
// using glademm V1.1.0c
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /usr/src/sean/greendb/app/greenapp.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/greenWin.hh and./src/greenWin.cc

#ifndef _GREENWIN_GLADE_HH
#  define _GREENWIN_GLADE_HH

#include <gtk--/window.h>

class greenWin_glade : public Gtk::Window
{  
protected:
        
        
        greenWin_glade();
        
        ~greenWin_glade();
};
#endif
