# This file was automatically generated by SWIG
package greendb;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package greendb;
bootstrap greendb;
package greendb;
@EXPORT = qw( );
1;
