<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.17u-20021128-1508
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

global $GREENDB_LOADED__;
if ($GREENDB_LOADED__) return;
$GREENDB_LOADED__ = true;

/* if our extension has not been loaded, do what we can */
if (!extension_loaded("php_greendb")) {
	if (!dl("php_greendb.so")) return;
}



?>
